spring:
  # Make sure to specify `optional:`.
  config.import: "optional:configserver:"
  cloud.config:
    # Find the configuration server via service discovery.
    discovery:
      enabled: true
      service-id: config
    # Retry policy
    retry:
      initial-interval: 1000
      max-attempts: 6
      max-interval: 16000
      multiplier: 2.0
    # Prevents the application from running
    # until all configuration information is obtained through retries.
    fail-fast: true