services:
  vault:
    image: hashicorp/vault:1.18
    command: server
    ports:
      - "8200:8200"
    volumes:
      - secrets:/vault/file
      - ./policies:/vault/policies
      - ./config.hcl:/vault/config/config.hcl
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: http://vault:8200
    networks:
      - vault

volumes:
  secrets:

networks:
  vault:
    name: vault