### Default ###
management:
  endpoint:
    health.probes.enabled: true
  endpoints:
    web.base-path: /hyd

---

### For production(single, cluster) ###

spring.config.activate.on-profile: single | cluster

management:
  endpoints:
    access.default: none
    web.exposure.include:
      - info
      - health
  endpoint:
    # Enable "health" endpoint without details.
    # For more endpoints, see:
    #   https://docs.spring.io/spring-boot/reference/actuator/endpoints.html
    health:
      show-details: never
      access: read_only
    # Enable "info" endpoint.
    info:
      access: read_only
  # Enable only build info.
  info:
    defaults.enabled: false
    build.enabled: true

---

### For development ###
spring.config.activate.on-profile: development

management:
  endpoint:
    health.show-details: always
  endpoints:
    web.exposure.include: "*"