spring.security.oauth2.client.registration:
  google:
    client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
    client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
    scope:
      - email

server.servlet.session.cookie:
  http-only: true
  same-site: lax
  name: tmid